In [2]:
import yfinance as yf
import pandas as pd
import numpy as np
from IPython.display import display
from pathlib import Path

In [ ]:
historical_data_intervals = ["2m", "1h"]

In [4]:
#Import Tickers of Interest
stock_tickers = ["AAPL", "NVDA", "AMZN", #TECH
               "AXP", "BRK-B", "JPM", #BANKING
               "JNJ", "PFE", "UNH", #HEALTHCARE
               "PG", "WMT", "KO", #RETAIL
               "GE", "CAT", "LMT", #INDUSTRIAL/AEROSPACE
               "SONY", "SSNLF", "NVO",  #INTERNATIONAL
               "SPY", "VOO", "IVV", "QQQ"] #ETFs

ticker_background_data = {}

#Create dataframe of info on each stock ticker
for ticker in stock_tickers:
    ticker_object = yf.Ticker(ticker)

    #Obtain Company Data
    temp = pd.DataFrame.from_dict(ticker_object.info, orient="index")
    temp.reset_index(inplace=True)
    temp.columns = ["Attribute", "Recent"]
    ticker_background_data[ticker] = temp



#Clean backgound df information
ticker_background_data_df = pd.concat(ticker_background_data).reset_index()
ticker_background_data_df = ticker_background_data_df.drop(columns = ['level_1'])
ticker_background_data_df.columns = ["Ticker", "Attribute", "Value"]

pd.set_option("display.max_columns", None)

ticker_background_data_df

     Ticker         Attribute                        Value
0      AAPL          address1           One Apple Park Way
1      AAPL              city                    Cupertino
2      AAPL             state                           CA
3      AAPL               zip                        95014
4      AAPL           country                United States
...     ...               ...                          ...
3639    QQQ            market                    us_market
3640    QQQ      esgPopulated                        False
3641    QQQ         shortName  Invesco QQQ Trust, Series 1
3642    QQQ          longName            Invesco QQQ Trust
3643    QQQ  trailingPegRatio                         None

[3644 rows x 3 columns]

In [ ]:
trading_data_by_interval = {}


for interval in historical_data_intervals:

    ticker_trading_data = []

    for ticker in stock_tickers:

        ticker_object = yf.Ticker(ticker)

        # Obtain different granularities of trading data for different training stages
        temp = ticker_object.history(period="max", interval=interval)
        temp["Ticker"] = ticker

        if not temp.empty:
            ticker_trading_data.append(temp)

    print(f"Interval {interval} download complete.")


    trading_data_by_interval[interval] = pd.concat(ticker_trading_data)
    
for name, df in trading_data_by_interval.items():
    print(f"=== {name} ===")
    display(df)

Interval 1m download complete.
Interval 2m download complete.
Interval 1h download complete.
=== 1m ===

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Ticker,Capital Gains
Datetime,,,,,,,,,
2026-07-27 09:30:00-04:00,334.899994,336.700012,334.100006,335.334991,1876287,0.0,0.0,AAPL,NaN
2026-07-27 09:31:00-04:00,335.420013,336.380005,335.119995,335.500000,271943,0.0,0.0,AAPL,NaN
2026-07-27 09:32:00-04:00,335.510010,336.947998,335.510010,336.739685,236166,0.0,0.0,AAPL,NaN
2026-07-27 09:33:00-04:00,336.700012,337.119995,336.477295,336.684998,250700,0.0,0.0,AAPL,NaN
2026-07-27 09:34:00-04:00,336.750000,337.040009,335.350494,335.545013,292933,0.0,0.0,AAPL,NaN
...,...,...,...,...,...,...,...,...,...
2026-07-31 15:55:00-04:00,690.570007,690.599976,689.369995,689.570007,193221,0.0,0.0,QQQ,0.0
2026-07-31 15:56:00-04:00,689.590027,689.820007,689.530029,689.669983,152350,0.0,0.0,QQQ,0.0
2026-07-31 15:57:00-04:00,689.650024,689.780029,689.200012,689.200012,226956,0.0,0.0,QQQ,0.0
2026-07-31 15:58:00-04:00,689.229980,689.409973,689.049988,689.270020,174413,0.0,0.0,QQQ,0.0
2026-07-31 15:59:00-04:00,689.320007,689.346008,687.479980,688.010010,685554,0.0,0.0,QQQ,0.0

=== 2m ===

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Ticker,Capital Gains
Datetime,,,,,,,,,
2026-06-18 09:30:00-04:00,298.440002,300.459900,298.070007,300.200012,11526691,0.0,0.0,AAPL,NaN
2026-06-18 09:32:00-04:00,300.250000,300.309998,298.399994,298.440002,492441,0.0,0.0,AAPL,NaN
2026-06-18 09:34:00-04:00,298.390106,298.619995,296.750000,296.760010,952473,0.0,0.0,AAPL,NaN
2026-06-18 09:36:00-04:00,296.785004,296.825012,295.619995,296.450104,626938,0.0,0.0,AAPL,NaN
2026-06-18 09:38:00-04:00,296.450012,296.959991,296.250000,296.364990,406277,0.0,0.0,AAPL,NaN
...,...,...,...,...,...,...,...,...,...
2026-07-31 15:50:00-04:00,690.500000,690.739990,689.650024,689.844971,425055,0.0,0.0,QQQ,0.0
2026-07-31 15:52:00-04:00,689.840027,690.679993,689.830017,690.590027,223707,0.0,0.0,QQQ,0.0
2026-07-31 15:54:00-04:00,690.679993,690.880005,689.369995,689.570007,353975,0.0,0.0,QQQ,0.0
2026-07-31 15:56:00-04:00,689.590027,689.820007,689.200012,689.200012,379306,0.0,0.0,QQQ,0.0
2026-07-31 15:58:00-04:00,689.229980,689.409973,687.479980,688.010010,859967,0.0,0.0,QQQ,0.0

=== 1h ===

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Ticker,Capital Gains
Datetime,,,,,,,,,
2024-08-02 09:30:00-04:00,219.149994,224.414993,217.710007,222.654999,29536982,0.0,0.0,AAPL,NaN
2024-08-02 10:30:00-04:00,222.630005,224.379898,221.759995,222.830002,14319380,0.0,0.0,AAPL,NaN
2024-08-02 11:30:00-04:00,222.860001,224.720001,221.419998,224.619995,9098444,0.0,0.0,AAPL,NaN
2024-08-02 12:30:00-04:00,224.615005,225.600006,223.449997,224.639999,7487153,0.0,0.0,AAPL,NaN
2024-08-02 13:30:00-04:00,224.630005,225.005005,221.910004,223.434998,7549443,0.0,0.0,AAPL,NaN
...,...,...,...,...,...,...,...,...,...
2026-07-31 11:30:00-04:00,681.719971,686.929993,680.940002,686.929993,3657729,0.0,0.0,QQQ,0.0
2026-07-31 12:30:00-04:00,686.950012,689.719971,685.630005,689.359985,3527804,0.0,0.0,QQQ,0.0
2026-07-31 13:30:00-04:00,689.369995,690.349976,687.760010,688.380005,3654902,0.0,0.0,QQQ,0.0
2026-07-31 14:30:00-04:00,688.580017,690.250000,688.030029,689.700012,3737502,0.0,0.0,QQQ,0.0
2026-07-31 15:30:00-04:00,689.669983,690.880005,687.479980,688.010010,4968185,0.0,0.0,QQQ,0.0

In [ ]:
#Export the data 
output_dir = Path("../yfinance/data")

for name, df in trading_data_by_interval.items():
    df.to_csv(output_dir / f"{name}_interval_trading_data.csv")

ticker_background_data_df.to_csv(output_dir / "ticker_background_data_df.csv")